"Resource\OptionsSubRendererGL33.res"
{
	"ShadowsTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"ShadowsTitle"
		"xpos"		"16"
		"ypos"		"8"
		"wide"		"460"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowsHeader"
		"textAlignment"		"west"
		"brighttext"		"1"
	}
	"ShadowsDivider"
	{
		"ControlName"		"Divider"
		"fieldName"		"ShadowsDivider"
		"xpos"		"16"
		"ypos"		"28"
		"wide"		"460"
		"tall"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ShadowMap"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShadowMap"
		"xpos"		"16"
		"ypos"		"38"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GSX_ShadowMap"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"ShadowLocals"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShadowLocals"
		"xpos"		"245"
		"ypos"		"38"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"#GSX_ShadowLocals"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"ShadowDlights"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShadowDlights"
		"xpos"		"16"
		"ypos"		"64"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"#GSX_ShadowDlights"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"QualityTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"QualityTitle"
		"xpos"		"16"
		"ypos"		"94"
		"wide"		"215"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowQuality"
		"textAlignment"		"west"
		"brighttext"		"1"
	}
	"QualitySlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"QualitySlider"
		"xpos"		"16"
		"ypos"		"114"
		"wide"		"170"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
	}
	"QualityLabel"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"QualityLabel"
		"xpos"		"190"
		"ypos"		"116"
		"wide"		"40"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"	"1"
	}
	"StrengthTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"StrengthTitle"
		"xpos"		"245"
		"ypos"		"94"
		"wide"		"215"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowStrength"
		"textAlignment"		"west"
		"brighttext"		"1"
	}
	"StrengthSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"StrengthSlider"
		"xpos"		"245"
		"ypos"		"114"
		"wide"		"170"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
	}
	"StrengthLabel"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"StrengthLabel"
		"xpos"		"419"
		"ypos"		"116"
		"wide"		"40"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"	"1"
	}
	"EffectsTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"EffectsTitle"
		"xpos"		"16"
		"ypos"		"164"
		"wide"		"460"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ScreenFxHeader"
		"textAlignment"		"west"
		"brighttext"		"1"
	}
	"EffectsDivider"
	{
		"ControlName"		"Divider"
		"fieldName"		"EffectsDivider"
		"xpos"		"16"
		"ypos"		"184"
		"wide"		"460"
		"tall"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ScreenFx"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ScreenFx"
		"xpos"		"16"
		"ypos"		"194"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		"#GSX_ScreenFx"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"MenuBlur"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MenuBlur"
		"xpos"		"245"
		"ypos"		"194"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"labelText"		"#GSX_MenuBlur"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"UnderwaterFx"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"UnderwaterFx"
		"xpos"		"16"
		"ypos"		"220"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		"#GSX_UnderwaterFx"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"UnderwaterPixelate"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"UnderwaterPixelate"
		"xpos"		"245"
		"ypos"		"220"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"9"
		"labelText"		"#GSX_UnderwaterPixelate"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"SoftWater"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"SoftWater"
		"xpos"		"16"
		"ypos"		"246"
		"wide"		"215"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"10"
		"labelText"		"#GSX_SoftWater"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
}
