"Resource\OptionsSubRendererGL33.res"
{
	"ShadowsTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"ShadowsTitle"
		"xpos"		"16"
		"ypos"		"8"
		"wide"		"218"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowsHeader"
		"textAlignment"		"west"
		"brighttext"		"1"
	}
	"EffectsTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"EffectsTitle"
		"xpos"		"258"
		"ypos"		"8"
		"wide"		"218"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ScreenFxHeader"
		"textAlignment"		"west"
		"brighttext"		"1"
	}
	"ShadowsDivider"
	{
		"ControlName"		"Divider"
		"fieldName"		"ShadowsDivider"
		"xpos"		"16"
		"ypos"		"29"
		"wide"		"218"
		"tall"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"EffectsDivider"
	{
		"ControlName"		"Divider"
		"fieldName"		"EffectsDivider"
		"xpos"		"258"
		"ypos"		"29"
		"wide"		"218"
		"tall"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ShadowMap"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShadowMap"
		"xpos"		"16"
		"ypos"		"34"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GSX_ShadowMap"
		"textAlignment"		"west"
	}
	"ShadowFirstPerson"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShadowFirstPerson"
		"xpos"		"16"
		"ypos"		"58"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"#GSX_ShadowFirstPerson"
		"textAlignment"		"west"
	}
	"ShadowBrush"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShadowBrush"
		"xpos"		"16"
		"ypos"		"82"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"#GSX_ShadowBrush"
		"textAlignment"		"west"
	}
	"QualityTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"QualityTitle"
		"xpos"		"16"
		"ypos"		"108"
		"wide"		"218"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowQuality"
		"textAlignment"		"west"
	}
	"ShadowQuality"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ShadowQuality"
		"xpos"		"16"
		"ypos"		"130"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"editable"		"0"
	}
	"StrengthTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"StrengthTitle"
		"xpos"		"16"
		"ypos"		"162"
		"wide"		"170"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowStrength"
		"textAlignment"		"west"
	}
	"ShadowStrengthValue"
	{
		"ControlName"		"Label"
		"fieldName"		"ShadowStrengthValue"
		"xpos"		"190"
		"ypos"		"162"
		"wide"		"44"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"east"
	}
	"ShadowStrength"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"ShadowStrength"
		"xpos"		"16"
		"ypos"		"184"
		"wide"		"218"
		"tall"		"42"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"leftText"		"0%"
		"rightText"		"100%"
	}
	"DistanceTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"DistanceTitle"
		"xpos"		"16"
		"ypos"		"232"
		"wide"		"140"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowDistance"
		"textAlignment"		"west"
	}
	"ShadowDistance"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ShadowDistance"
		"xpos"		"160"
		"ypos"		"230"
		"wide"		"74"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"NumericInputOnly"		"1"
		"maxchars"		"12"
		"editable"		"1"
	}
	"LengthTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"LengthTitle"
		"xpos"		"16"
		"ypos"		"264"
		"wide"		"140"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_ShadowLength"
		"textAlignment"		"west"
	}
	"ShadowLength"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ShadowLength"
		"xpos"		"160"
		"ypos"		"262"
		"wide"		"74"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"NumericInputOnly"		"1"
		"maxchars"		"12"
		"editable"		"1"
	}
	"ScreenFx"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ScreenFx"
		"xpos"		"258"
		"ypos"		"34"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		"#GSX_ScreenFx"
		"textAlignment"		"west"
	}
	"MenuBlur"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MenuBlur"
		"xpos"		"258"
		"ypos"		"58"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"9"
		"labelText"		"#GSX_MenuBlur"
		"textAlignment"		"west"
	}
	"MotionBlur"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MotionBlur"
		"xpos"		"258"
		"ypos"		"82"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"10"
		"labelText"		"#GSX_MotionBlur"
		"textAlignment"		"west"
	}
	"MotionStrengthTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"MotionStrengthTitle"
		"xpos"		"258"
		"ypos"		"108"
		"wide"		"174"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_MotionBlurStrength"
		"textAlignment"		"west"
	}
	"MotionStrengthValue"
	{
		"ControlName"		"Label"
		"fieldName"		"MotionStrengthValue"
		"xpos"		"434"
		"ypos"		"108"
		"wide"		"42"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"east"
	}
	"MotionStrength"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"MotionStrength"
		"xpos"		"258"
		"ypos"		"130"
		"wide"		"218"
		"tall"		"42"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"11"
		"leftText"		"0%"
		"rightText"		"100%"
	}
	"UnderwaterTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"UnderwaterTitle"
		"xpos"		"258"
		"ypos"		"184"
		"wide"		"218"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GSX_UnderwaterMode"
		"textAlignment"		"west"
	}
	"Underwater"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Underwater"
		"xpos"		"258"
		"ypos"		"206"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"12"
		"editable"		"0"
	}
	"SoftWater"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"SoftWater"
		"xpos"		"258"
		"ypos"		"248"
		"wide"		"218"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"13"
		"labelText"		"#GSX_SoftWater"
		"textAlignment"		"west"
	}
}
