; This file contains the values for every supported limit
; adjustable by the in-game limit adjuster.
; After changing any of these values, you have to restart the game.

; CREATED BY xWhitey
; EXTENDED BY ScriptedSnark
; GSX

[Limits]
MAX_TEMP_ENTITIES = 1536
MAX_DLIGHTS = 64
MAX_ELIGHTS = 64
MAX_LIGHTSTYLES = 256
MAX_GLTEXTURES = 10000
SPR_MAX_SPRITES = 256